/**
 * SHARED ERROR CODES - Single source of truth
 * Used by both Backend and Frontend to ensure consistency
 */

export enum ErrorCode {
  // Generic / Unknown
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication
  UNAUTHORIZED = 'UNAUTHORIZED',
  AUTH_FAILED = 'AUTH_FAILED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // Authorization
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Resource
  NOT_FOUND = 'NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // Database
  DATABASE_ERROR = 'DATABASE_ERROR',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  CAST_ERROR = 'CAST_ERROR',
  SCHEMA_VALIDATION_ERROR = 'SCHEMA_VALIDATION_ERROR',
  CONNECTION_ERROR = 'CONNECTION_ERROR',

  // External APIs
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  PAYMENT_ERROR = 'PAYMENT_ERROR',
  EMAIL_ERROR = 'EMAIL_ERROR',
  THIRD_PARTY_ERROR = 'THIRD_PARTY_ERROR',

  // Network
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  DNS_ERROR = 'DNS_ERROR',
  OFFLINE = 'OFFLINE',

  // File Operations
  FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR',
  FILE_SIZE_EXCEEDED = 'FILE_SIZE_EXCEEDED',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',

  // Frontend Specific
  CHUNK_LOAD_ERROR = 'CHUNK_LOAD_ERROR',
  BUILD_ERROR = 'BUILD_ERROR',
  RUNTIME_ERROR = 'RUNTIME_ERROR',
  UI_CRASH = 'UI_CRASH',

  // Business Logic
  BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
  OPERATION_FAILED = 'OPERATION_FAILED',
  CONFLICT = 'CONFLICT',
}

export const HTTP_STATUS_CODES: Record<ErrorCode, number> = {
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.UNKNOWN_ERROR]: 500,

  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 400,

  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.AUTH_FAILED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,

  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,

  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,

  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.DUPLICATE_KEY]: 409,
  [ErrorCode.CAST_ERROR]: 400,
  [ErrorCode.SCHEMA_VALIDATION_ERROR]: 400,
  [ErrorCode.CONNECTION_ERROR]: 500,

  [ErrorCode.EXTERNAL_API_ERROR]: 502,
  [ErrorCode.PAYMENT_ERROR]: 502,
  [ErrorCode.EMAIL_ERROR]: 500,
  [ErrorCode.THIRD_PARTY_ERROR]: 502,

  [ErrorCode.NETWORK_ERROR]: 503,
  [ErrorCode.TIMEOUT_ERROR]: 504,
  [ErrorCode.DNS_ERROR]: 503,
  [ErrorCode.OFFLINE]: 503,

  [ErrorCode.FILE_UPLOAD_ERROR]: 400,
  [ErrorCode.FILE_SIZE_EXCEEDED]: 413,
  [ErrorCode.INVALID_FILE_TYPE]: 400,

  [ErrorCode.CHUNK_LOAD_ERROR]: 500,
  [ErrorCode.BUILD_ERROR]: 500,
  [ErrorCode.RUNTIME_ERROR]: 500,
  [ErrorCode.UI_CRASH]: 500,

  [ErrorCode.BUSINESS_LOGIC_ERROR]: 400,
  [ErrorCode.OPERATION_FAILED]: 400,
  [ErrorCode.CONFLICT]: 409,
};
